"""Initial schema: projects, tasks, runs, traces, model calls, benchmarks.

Mirrors the ORM models in `apps/api/db.py` as of Phase 4 (PLAN.md section 15).
Hand-written rather than autogenerated -- no live Postgres instance was
available in the environment this was authored in, so it has not been run
against a real database; it has been checked against `apps/api/db.py` field by
field and exercised structurally via `PostgresStore` against SQLite in
`tests/unit/test_db_store.py`. Verify with `alembic upgrade head` before
relying on it in production.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-21
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "decision_tasks",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("project_id", sa.String(32), sa.ForeignKey("projects.id"), nullable=True),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("version", sa.String(32), nullable=False, server_default="1"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("definition", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_decision_tasks_name", "decision_tasks", ["name"])

    op.create_table(
        "decision_policies",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("definition", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "decision_runs",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("task_ref", sa.String(160), nullable=True),
        sa.Column("provider", sa.String(64), nullable=True),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("execution_status", sa.String(32), nullable=False),
        sa.Column("validation_status", sa.String(32), nullable=False),
        sa.Column("decisions", postgresql.JSONB(), nullable=False),
        sa.Column("confidence", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("used_fallback", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_decision_runs_task_ref", "decision_runs", ["task_ref"])
    op.create_index("ix_decision_runs_execution_status", "decision_runs", ["execution_status"])
    op.create_index("ix_decision_runs_created_at", "decision_runs", ["created_at"])

    op.create_table(
        "decision_traces",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("run_id", sa.String(32), sa.ForeignKey("decision_runs.id"), nullable=False),
        sa.Column("events", postgresql.JSONB(), nullable=False),
        # NULL unless input capture is explicitly enabled; see PLAN.md section 15.
        sa.Column("state", postgresql.JSONB(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_decision_traces_run_id", "decision_traces", ["run_id"])

    op.create_table(
        "model_calls",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("run_id", sa.String(32), sa.ForeignKey("decision_runs.id"), nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_model_calls_run_id", "model_calls", ["run_id"])

    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("task_ref", sa.String(160), nullable=False),
        sa.Column("dataset_ref", sa.String(160), nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("policy", postgresql.JSONB(), nullable=False),
        sa.Column("report", postgresql.JSONB(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_benchmark_runs_task_ref", "benchmark_runs", ["task_ref"])
    op.create_index("ix_benchmark_runs_dataset_ref", "benchmark_runs", ["dataset_ref"])
    op.create_index("ix_benchmark_runs_provider", "benchmark_runs", ["provider"])
    op.create_index("ix_benchmark_runs_status", "benchmark_runs", ["status"])

    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column(
            "benchmark_run_id", sa.String(32), sa.ForeignKey("benchmark_runs.id"), nullable=False
        ),
        sa.Column("question", sa.String(128), nullable=False),
        sa.Column("metric", sa.String(64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("scored_examples", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_evaluation_results_benchmark_run_id", "evaluation_results", ["benchmark_run_id"]
    )


def downgrade() -> None:
    op.drop_table("evaluation_results")
    op.drop_table("benchmark_runs")
    op.drop_table("model_calls")
    op.drop_table("decision_traces")
    op.drop_table("decision_runs")
    op.drop_table("decision_policies")
    op.drop_table("decision_tasks")
    op.drop_table("projects")
